# Generated by Django 4.1.7 on 2023-03-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('wiki_title', models.CharField(max_length=200)),
                ('target_lang', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
