# Generated by Django 4.1.7 on 2023-03-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_translator_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assigned_to',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_id', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=100)),
                ('original_sentence', models.CharField(max_length=1000)),
                ('translated_sentence', models.CharField(default=None, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki_translator_api.project')),
            ],
        ),
    ]
