# Generated by Django 4.1.7 on 2023-03-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_translator_api', '0002_alter_project_assigned_to_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='translated_sentence',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
