# Generated by Django 4.1.7 on 2023-03-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_translator_api', '0003_alter_sentence_translated_sentence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='created_by',
        ),
    ]
