# Generated by Django 4.1.7 on 2023-03-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_translator_api', '0004_remove_sentence_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='id',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentence_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
